Blackbelt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.travelbuddy.urls', namespace="travelbuddy")),
    url(r'^login/', include('apps.login.urls', namespace="login")),
]

apps/login/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

#app_name='login_app'
urlpatterns =[
    #url(r'^$', views.index, name='index'),
    url(r'^registration$', views.log_register, name='register'),
    url(r'^login$', views.log_register, name='login'),
    url(r'^logout$', views.logout, name='logout'),

]

apps/travelbuddy/urls.py
from django.conf.urls import url
from . import views

app_name="travelbuddy"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^travels$', views.travels, name='travels'),
    url(r'^trip_add$', views.trip_add, name='trip_add'),
    url(r'^join_trip/(?P<trip_id>\d+)$', views.join_trip, name='join_trip'),
    url(r'^destination/(?P<id>\d+)$', views.destination, name='destination'),
    url(r'^create_trip$', views.create_trip, name='create_trip'),
]

apps/travelbuddy/models.py
 # -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..login.models import Login
from datetime import datetime

# Create your models here.
class TripManager(models.Manager):
    def create_trip(self, data, id):
        current_date = datetime.now().strftime('%Y-%m-%d')
        errors = []
        if len(data['destination']) < 2:
            errors.append(['destination', "Destination name must be at least two characters in length."])
        if data['description'] == "":
            errors.append(['description', "Please enter a description."])
        if data['travelDateFrom'] < current_date:
            errors.append(['description', "Please enter a departure date greater than or equal to today's date."])
        if data['travelDateTo'] <= data['travelDateFrom']:
            errors.append(['description', "Please enter a return date greater than your departure date."])
        if errors:
            return [False, errors]
        else:
            user_id = Login.objects.get(id=id)
            NewTrip = Trip(destination=data['destination'], description=data['description'], user_id=user_id, travelDateFrom=data['travelDateFrom'], travelDateTo=data['travelDateTo'])
            NewTrip.save()
            myTrip = Travel(trip_id=Trip.objects.last(), user_id=user_id)
            myTrip.save()
            return [True, myTrip]

class Trip(models.Model):
    destination = models.CharField(max_length=500)
    description = models.CharField(max_length=500)
    travelDateFrom = models.DateField()
    travelDateTo = models.DateField()
    user_id = models.ForeignKey('login.Login', related_name='planner', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TripManager()

    def __str__(self):
        return 'ID: %s | Destination: %s | Description: %s | Departure: %s | Return: %s | Created: %s | Updated: %s' % (self.id, self.destination, self.description, self.travelDateFrom, self.travelDateTo, self.created_at, self.updated_at)

class TravelManager(models.Manager):
    def join_trip(self, user_id, trip_id):
        user_id = Login.objects.get(id=user_id)
        trip_id = Trip.objects.get(id=trip_id)
        Travel.objects.create(user_id=user_id, trip_id=trip_id)

class Travel(models.Model):
    user_id = models.ForeignKey('login.Login', related_name='PersonTraveling', on_delete=models.CASCADE)
    trip_id = models.ForeignKey('travelbuddy.Trip', related_name='TripSelected', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TravelManager()

    def __str__(self):
        return 'ID: %s | User ID: %s | Trip ID: %s | Created: %s | Updated: %s' % (self.id, self.user_id, self.trip_id, self.created_at, self.updated_at)

apps/travelbuddy/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.contrib import messages
from django.shortcuts import render, redirect
from . models import Trip, Travel
from ..login.models import Login

# Create your views here.
def index(request):
    return render(request, "travelbuddy/index.html")

def travels(request):
    if 'user' not in request.session:
        return redirect('travelbuddy:index')
    context = {
        "user_trips": Travel.objects.all().order_by('trip_id__travelDateFrom'),
    }
    return render(request, "travelbuddy/travels.html", context)

def trip_add(request):
    if 'user' not in request.session:
        return redirect('travelbuddy:index')
    return render(request, "travelbuddy/trip_add.html")

def create_trip(request):
    if request.method == "POST":
        response = Trip.objects.create_trip(request.POST, request.session['user']['id'])
    if not response[0]:
        for error in response[1]:
            messages.error(request, error[1])
        return redirect('travelbuddy:trip_add')
    else:
        return redirect('travelbuddy:travels')

def join_trip(request, trip_id):
    Travel.objects.join_trip(request.session['user']['id'], trip_id)
    return redirect('travelbuddy:travels')

def destination(request, id):
    if 'user' not in request.session:
        return redirect('travelbuddy:index')
    try:
        destination_check = Travel.objects.get(id=id)
    except:
        return redirect('travelbuddy:travels')
    if request.method == 'GET':
        context = {
            "destination": Trip.objects.order_by(id).get(id=id),
            "userTrips": Travel.objects.all(),
        }
        return render(request, "travelbuddy/destination.html", context)

apps/travelbuddy/templates/travelbuddy/destination.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travelbuddy/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="{% static 'travelbuddy/jquery-2.2.3.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/jquery-ui.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/materialize.js' %}"></script>
  </head>
  <body>
      <div class="container">
        <div id="navbar">
          <ul class="navbar-form navbar-right">
            <li><a href="{% url 'travelbuddy:travels' %}">Home</a></li>
            <li><a href="{% url 'login:logout' %}" class="button">Log out</a></li>
          </ul>
        </div>
        {% if destination %}
        <h3>{{ destination.destination }}</h3>
        <p>Planned By: {{ destination.user_id.first_name }} {{ destination.user_id.last_name }}</p>
        <p>Description: {{ destination.description }}</p>
        <p>Travel Date From: {{ destination.travelDateFrom }}</p>
        <p>Travel Date To: {{ destination.travelDateTo }}</p>
        <h3>Other users joining the trip:</h3>
        <ul class="others">
        {% for other in userTrips %}
        {% if other.trip_id.id == destination.id %}
        {% if other.user_id.id != destination.user_id.id %}
          <li>{{ other.user_id.first_name }} {{ other.user_id.last_name }}</li>
          {% endif %}
          {% endif %}
        {% endfor %}
        </ul>
        {% else %}
        <p>No destination found.</p>
        {% endif %}
    </div> <!-- /container -->

  </body>
</html>

apps/travelbuddy/templates/travelbuddy/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to Travel buddy</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travelbuddy/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="{% static 'travelbuddy/jquery-2.2.3.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/jquery-ui.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/materialize.js' %}"></script>
  </head>
  <body>
    <div id ='wrapper'>
      <h2 id="welcome"> Welcome!</h2>
      {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
      {% endif %}
      <div id="registration">
        <h2>Registration</h2>
        <form action="login/registration" method="post">
            {% csrf_token %}
            <label for="">First Name</label><input type="text" name="first_name"><br>
            <label for="">Last Name</label><input type="text" name="last_name"><br>
            <label for="">Email</label><input type="text" name="email"><br>
            <label for="">Password</label><input type="password" name="password"><br>
            <label for="">Confirm Password</label><input type="password" name="password_confirmation"><br>
            {% csrf_token %}
            <button class="btn submit" name="carryon" value="register" type="submit">Submit</button>
          </form>
      </div>
      <div id= "login">
        <h2>Login</h2>
        <form action="{% url 'login:login' %}" method="post">
            {% csrf_token %}
            <label for="">Email</label><input type="text" name="email"><br>
            <label for="">Password</label><input type="password" name="password"><br>
            {% csrf_token %}
            <button class="btn submit" name="carryon" value="login" type="submit">Submit</button>
        </form>

      </div>

    </div>
  </body>
</html>

apps/travelbuddy/templates/travelbuddy/travels.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travel Dashboard</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travelbuddy/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="{% static 'travelbuddy/jquery-2.2.3.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/jquery-ui.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/materialize.js' %}"></script>
</head>
<body>
    <div class="container">
      <div id="navbar" >

          <a href="{% url 'login:logout' %}" class="button">Log out</a>

      </div>


    <!-- Main-->
    <div class="main">

        <h1>Hello, {{ request.session.user.first_name }}!</h1>

    </div>
    <h4> Your Trip Schedules</h4>
    <div id="userTrips">
      <h3>{{ travel.my_trips }}</h3>
      {% if travel.my_trips %}
      {% endif %}
      <table>
        <thead>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Plan</th>
        </thead>
      {% for trip in user_trips %}
      {% if trip.user_id.id == request.session.user.id %}
        <tr>
          <td><a href="destination/{{ trip.trip_id.id }}">{{trip.trip_id.destination}}</a></td>
          <td>{{ trip.trip_id.travelDateFrom }}</td>
          <td>{{ trip.trip_id.travelDateTo }}</td>
          <td>{{ trip.trip_id.description }}</td>
        </tr>
      {% endif %}
      {% empty %}
            <p>No trips planned.</p>
      {% endfor %}
      </table>
    </div>
    <h4>Other User's Travel Plans</h4>
    <div id="othersTrips">
      <table>
        <thead>
          <th>Name</th>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Do you want to join?</th>
        </thead>
        {% for trip in user_trips %}
        {% if trip.user_id.id != request.session.user.id %}
        <tr>
          <td>{{ trip.user_id.first_name }} {{ trip.user_id.last_name }}</td>
          <td><a href="destination/{{ trip.trip_id.id }}">{{ trip.trip_id.destination }}</a></td>
          <td>{{ trip.trip_id.travelDateFrom }}</td>
          <td>{{ trip.trip_id.travelDateTo }}</td>
          <td><a href="{% url 'travelbuddy:join_trip' trip.trip_id.id %}">Join</a></td>
        </tr>
        {% endif %}
        {% empty %}
          <p>No users found.</p>
        {% endfor %}
      </table>
    </div>
      <a href="{% url 'travelbuddy:trip_add' %}" >Add Travel Plan</a>

  </div>
</body>
</html>

apps/travelbuddy/templates/travelbuddy/trip_add.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Plan</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travelbuddy/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="{% static 'travelbuddy/jquery-2.2.3.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/jquery-ui.js' %}"></script>
  	<script src="{% static 'travelbuddy/js/materialize.js' %}"></script>
  </head>
  <body>
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="navbar-form navbar-right">
            <li><a href="{% url 'travelbuddy:travels' %}">Home</a></li>
            <li><a href="{% url 'login:logout' %}" class="button">Log out</a></li>
          </ul>
        </div>

    </nav>
      <div class="main">

        <h1>Add a trip</h1>

      </div>
    </div>

    <div id="user" class="container">
      {% if messages %}
      {% for message in messages%}
      <p class="error">{{ message }}</p>
      {% endfor %}
      {% endif %}
      <form action="{% url 'travelbuddy:create_trip' %}" method="POST" class="form-signin">
        <label for="destination">Destination</label>
        <input type="text" name="destination" placeholder="Destination" class="form-control" autofocus>
        <label for="description">Description</label>
        <textarea name="description" rows="4" cols="90" placeholder="Tell us about your trip."></textarea>
        <label for="travelDateFrom">Travel Date From</label>
        <input type="date" name="travelDateFrom" class="form-control">
        <label for="travelDateTo">Travel Date To</label>
        <input type="date" name="travelDateTo" class="form-control">
        {% csrf_token %}
        <button class="btn submit" value="add_trip" type="submit">Add</button>
      </form>
    </div> <!-- /container -->

  </body>
</html>